name: CI

# specify which github events will trigger CI build
on: push 

# Define a single job, build
jobs:

  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    # Specify the OS of the runner
    runs-on: ${{ matrix.os }}

    # Define our steps
    steps:

      # Firstly, check out the repo
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Setup the python environment
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Install all dependencies
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -e .
      # Run tests
      - name: Test with pytest
        run: |
          pytest --cov=inflammation.models tests/test_models.py

      # Linter
      - name: Check style with Pylint
        run: |
          python3 -m pylint --fail-under=0 -- reports=y inflammation